In [3]:
import pandas as pd

# Woking with JSON

In [4]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [5]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
"""
pd.read_json() : JSON data ko pandas DataFrame me convert karta hai.
"""

'\npd.read_json() : JSON data ko pandas DataFrame me convert karta hai.\n'

# Working with SQL

https://youtu.be/fFwRC-fapIU?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH&t=416

iss link m video start hogi vhn se khud smjh lena nhi aaya smjh

In [2]:
%pip install mysql.connector

"""
Ye command MySQL connector install karne ke liye hai.
! ka matlab hai notebook ke andar terminal/shell command run karna.
"""

Collecting mysql.connector
  Using cached mysql-connector-2.2.9.tar.gz (11.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=248051 sha256=bdffb88c13107c187b2cade8a85204878107375ea28a984a925bee181026fe40
  Stored in directory: c:\users\acer\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

'\nYe command MySQL connector install karne ke liye hai.\n! ka matlab hai notebook ke andar terminal/shell command run karna.\n'

In [ ]:
import mysql.connector
"""
Is module ki help se Python MySQL server se connection bana sakta hai.
mysql.connector Python ko MySQL database se connect karne ke liye use hota hai.
"""

:

In [ ]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')
"""
Ye line MySQL database se connection bana rahi hai.

Breakdown:
conn =
Connection object ko conn variable me store kar rahe hain.

mysql.connector.connect(...)
Ye function MySQL server se connect karta hai.

host='localhost'
Database server local machine par chal raha hai.

user='root'
MySQL username root hai.

password=''
Password blank hai. Matlab root user ka password empty hai.

database='world'
world naam ke database se connect karna hai.

Agar MySQL server running nahi hai, ya database world exist nahi karta, to error aayega.
"""

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 No connection could be made because the target machine actively refused it)

In [ ]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)
"""
Ye line SQL query run karke result pandas DataFrame me store karti hai.

Breakdown:
df =
Result ko df naam ke variable me store kar rahe hain.

pd.read_sql_query(...)
Pandas ka function hai jo SQL query ka result DataFrame me convert karta hai.

"SELECT * FROM countrylanguage"
Ye SQL query hai.
Meaning:
SELECT * FROM countrylanguage
countrylanguage table ke saare columns aur saari rows fetch karo.

conn
Ye wahi database connection hai jo Cell 10 me banaya tha.
Final result: df ke andar countrylanguage table ka data aa jayega.
"""

In [ ]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]